repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.1
    hooks:
    - id: flake8
    
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.812
  #   hooks:
  #     - id: mypy
  #       exclude: tests/|setup.py
  #       args: [--disallow-untyped-calls, --disallow-untyped-defs, --check-untyped-defs, --ignore-missing-imports, --no-strict-optional]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: "./run-mypy"
        language: system
        types: [python]
        require_serial: true
        verbose: true