repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/flake8.git
    rev: 3.9.1
    hooks:
    - id: flake8
      args: [--ignore=E741 W503 E203 E501 C901]
    
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: "./run-mypy"
        language: system
        types: [python]
        require_serial: true
        verbose: true
