repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.7.0'
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["--dev", "-f", "requirements.txt", "-o", "requirements.txt"]

  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/flake8.git
    rev: 7.0.0
    hooks:
    - id: flake8
      args: [--ignore=E741 W503 E203 E501 C901]
    
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: "./run-mypy"
        language: system
        types: [python]
        require_serial: true
        verbose: true
