name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  black:
    runs-on: ubuntu-latest
    # container: pytorch/pytorch:1.8.1-cuda11.1-cudnn8-runtime
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .
          # pip install 
      - name: pytest
        run: pytest tests